Build OpenVX API Docs:
  stage: build

  before_script:
   - uname -a
   - apt-get update -qq && apt-get install -y -qq wget unzip build-essential python3 git cmake bison flex libffi-dev zip
   - apt-get install -y -qq libgmp-dev libxml2-dev libgdk-pixbuf2.0-dev libcairo2-dev libpango1.0-dev ttf-lyx gtk-doc-tools ghostscript ruby-dev default-jre
   - gem install asciidoctor-diagram --pre
   - gem install asciidoctor-pdf --pre
   - gem install asciidoctor-mathematical --pre
   - gem install coderay --pre

  script:
    - cd docs
    - make all

  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
    - docs/out/*/*.pdf
    - docs/out/*/*/*.html
    expire_in: 2 weeks
