language: c
sudo: false
dist: bionic

os:
  - linux

compiler:
  - g++

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - lcov wget unzip build-essential python3 git cmake bison flex libffi-dev zip
            - libgmp-dev libxml2-dev libgdk-pixbuf2.0-dev libcairo2-dev libpango1.0-dev
            - fonts-lyx gtk-doc-tools ghostscript ruby-dev default-jre
  
branches:
  - openvx_1.3
  - openvx_1.2

before_script:
  - uname -a
  - gem install asciidoctor-diagram -v 1.5.18
  - gem install asciidoctor-pdf --pre
  - gem install asciidoctor-mathematical -v 0.3.5
  - gem install coderay --pre
  
script:
  - cd docs
  - make all

after_success:

notifications:
  email:
    - kiriti.nageshgowda@amd.com
    - jesse.villarreal@ti.com
    - radhakrishna.giduthuri@intel.com
    - brill@cadence.com
