language: c
sudo: false
dist: trusty

os:
  - linux

compiler:
  - gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - lcov wget unzip build-essential python3 git cmake bison flex libffi-dev zip
            - libgmp-dev libxml2-dev libgdk-pixbuf2.0-dev libcairo2-dev libpango1.0-dev 
            - ttf-lyx gtk-doc-tools ghostscript ruby-dev default-jre
  
branches:
  - openvx_1.2

before_script:
  - uname -a
  - gem install asciidoctor-diagram --pre
  - gem install asciidoctor-pdf --pre
  - gem install asciidoctor-mathematical --pre
  - gem install coderay --pre
  
script:
  - cd docs
  - make all

after_success:

notifications:
  email:
    - kiritigowda@gmail.com
