// Copyright (c) 2025 Khronos Group. This work is licensed under a
// Creative Commons Attribution 4.0 International License; see
// http://creativecommons.org/licenses/by/4.0/

= The OpenVX^(TM)^ Node Send Command Extension
:regtitle: pass:q,r[^®^]
The Khronos{regtitle} OpenVX Working Group; Contributor: Jesse Villarreal
:title-logo-image: images/Khronos_RGB.svg
:data-uri:
:icons: font
:toc2:
:toclevels: 3
:max-width: 100
:numbered:
:imagewidth: 800
:fullimagewidth: width="800"
:halfimagewidth: width="400"
:source-highlighter: coderay
// Various special / math symbols. This is easier to edit with than Unicode.
include::config/attribs.txt[]

// Paths to code examples and headers
:examples: examples
:headers: examples

image::images/OpenVX_RGB.svg[align="center",{halfimagewidth}]
include::copyright-spec.txt[]

<<<<

// Table of contents is inserted here
toc::[]

:leveloffset: 1
=  Extension to support sending asynchronous commands to nodes
[[sec_purpose]]
== Purpose
[[vx_status_e,vx_status_e]] [[vx_kernel,vx_kernel]] [[vxAddUserKernel,vxAddUserKernel]] [[vxVerifyGraph,vxVerifyGraph]][[VX_SUCCESS,VX_SUCCESS]] [[VX_FAILURE,VX_FAILURE]] [[VX_ERROR_INVALID_REFERENCE,VX_ERROR_INVALID_REFERENCE]] [[VX_ERROR_INVALID_PARAMETERS,VX_ERROR_INVALID_PARAMETERS]] [[VX_ERROR_INVALID_GRAPH,VX_ERROR_INVALID_GRAPH]] [[VX_ERROR_TIMEOUT,VX_ERROR_TIMEOUT]] [[VX_ERROR_GRAPH_NOT_VERIFIED,VX_ERROR_GRAPH_NOT_VERIFIED]] [[VX_ERROR_INVALID_NODE,VX_ERROR_INVALID_NODE]] [[VX_NODE_IS_REPLICATED,VX_NODE_IS_REPLICATED]] This document details an extension to any OpenVX version from 1.1 to 1.3.2, and references some APIs and symbols that may be found in those APIs: https://www.khronos.org/registry/OpenVX/.

[[node_send_command,Node Send Command Extension]] This extension is intended to define support for the application to send asynchronous commands to nodes within OpenVX.

[[sec_usecases]]
== Example Use Cases

* Automotive camera-based system: When the application detects that the speed of the car has crossed a threshold, it may want to send a command to a specific node in the graph to modify the camera frame rate, or algorithmic tuning parameter accordingly.  Since this information comes from outside of the OpenVX graph at a very infrequent rate, there needs to be a means by which the application can efficiently communicate this information to the node in the graph. 
* If a node has triggered an error event, then the application may want to query the node which triggered the event to get more information about the type of error so that it can take corrective action.
* An application may want to periodically trigger and report results of some kind of safety diagnostic for a node.

[[sec_background]]
== Background
Prior to this extension, the only standard way that an application has to send commands to an OpenVX node is through input and output parameters.

.*Node Input Parameters*
- For example, if an application wanted to modify the behavior of a node at run-time, it would need to first ensure that there is an input parameter to the node which can contain the control commands that the application needs to update.  Then, at run-time, in between graph process calls, the application can call the specific input object map or copy calls to update the input data object.

.*Node Output Parameters*
- Likewise, if the application needed to get some information from the node, it would need to first ensure that there is an output parameter to the node which the node can fill for every frame to contain any information that the application may need to access.

[[sec_problem]]
=== Limitations in Existing Specification
If the application only needs to send commands, or receive node specific information rarely, the node has to be instrumented with these extra parameters to always consider the input and write the output, even when this is not needed by the application.  Depending on the cost of consuming this input and/or providing this output, this could be a very inefficient use of resources.

Furthermore, when pipelining is used, the application is not able to write to or read from a node input or output unless the object is treated as a graph parameter.  This further puts additional burden on the application to continuously enqueue and dequeue these parameters when it most of the time may not need to since the input and outputs only need to be rarely asynchronously accessed. 

[[sec_design]]
== Summary

In summary, this extension supplies functions to:

* Register a new command callback function pointer to a user kernel.
* Send a command to a node, including any replicas it may have

[[sec_acknowledge]]
== Acknowledgements

This specification would not be possible without the contributions from this
partial list of the following individuals from the Khronos Working Group and
the companies that they represented at the time:

  * Kiriti Nagesh Gowda - AMD
  * Viktor Gyenes - AI Motive
  * Raphael Cano - Robert Bosch GmbH
  * Stephen Ramm - ETAS (Robert Bosch GmbH)
  * Jesse Villarreal - TI
  
[[module_documentation]]
= Module Documentation

// tag::group_node_send_command:summary[]
*Macros*

  * `<<VX_TIMEOUT_NO_WAIT,VX_TIMEOUT_NO_WAIT>>`
  * `<<VX_TIMEOUT_WAIT_FOREVER,VX_TIMEOUT_WAIT_FOREVER>>`
  * `<<VX_CONTROL_CMD_SEND_TO_ALL_REPLICATED_NODES,VX_CONTROL_CMD_SEND_TO_ALL_REPLICATED_NODES>>`
  * `<<VX_NODE_NUM_WITH_REPLICAS,VX_NODE_NUM_WITH_REPLICAS>>`

*Typedefs*

  * `<<vx_kernel_command_f>>`

*Functions*

  * `<<vxAddCommandToKernel>>`
  * `<<vxNodeSendCommand>>`

// end::group_node_send_command:summary[]

// tag::group_node_send_command:details[]
== Macros

// tag::refpage:VX_TIMEOUT_NO_WAIT[]
// [desc='',type='defines']
=== VX_TIMEOUT_NO_WAIT
indexterm:[Node Send Command API, VX_TIMEOUT_NO_WAIT]
// Brief text:
Constant to indicate that a timeout parameter to an api should check and not wait for the call to complete

include::api/defines/VX_TIMEOUT_NO_WAIT.txt[]

// end::refpage:VX_TIMEOUT_NO_WAIT[]


// tag::refpage:VX_TIMEOUT_WAIT_FOREVER[]
// [desc='',type='defines']
=== VX_TIMEOUT_WAIT_FOREVER
indexterm:[Node Send Command API, VX_TIMEOUT_WAIT_FOREVER]
// Brief text:
Constant to indicate that a timeout parameter to an api should wait forever for the call to complete

include::api/defines/VX_TIMEOUT_WAIT_FOREVER.txt[]

// end::refpage:VX_TIMEOUT_WAIT_FOREVER[]


// tag::refpage:VX_CONTROL_CMD_SEND_TO_ALL_REPLICATED_NODES[]
// [desc='',type='defines']
=== VX_CONTROL_CMD_SEND_TO_ALL_REPLICATED_NODES
indexterm:[Node Send Command API, VX_CONTROL_CMD_SEND_TO_ALL_REPLICATED_NODES]
// Brief text:
When sending a control command to a replicated node, this can be used to send control command to all replicated node.

include::api/defines/VX_CONTROL_CMD_SEND_TO_ALL_REPLICATED_NODES.txt[]

// end::refpage:VX_CONTROL_CMD_SEND_TO_ALL_REPLICATED_NODES[]


// tag::refpage:VX_NODE_NUM_WITH_REPLICAS[]
// [desc='',type='defines']
=== VX_NODE_NUM_WITH_REPLICAS
indexterm:[Node Send Command API, VX_NODE_NUM_WITH_REPLICAS]
// Brief text:
Indicates the number of nodes associated with this node, including first_node and its replicas. A value of '0' indicates that the node has been optimized away; a value of '1' indicates that the node is not replicated; a value greater than 1 indicates that the node is replicated.  Read-only. Use a vx_uint32 parameter.

include::api/defines/VX_NODE_NUM_WITH_REPLICAS.txt[]

// end::refpage:VX_NODE_NUM_WITH_REPLICAS[]

== Typedefs

// tag::refpage:vx_kernel_command_f[]
// [desc='',type='basetypes']
=== vx_kernel_command_f

// Brief text:
`[*REQ-NC01*]`[[REQ-NC01]] The pointer to the control command function for the kernel.

include::api/basetypes/vx_kernel_command_f.txt[]

// Detailed text:
`[*REQ-NC02*]`[[REQ-NC02]] It is the responsibility of this callback to verify that the command passed and type and size of the references that are passed are valid prior to processing.

*Parameters*

  * `[in]` _node_ - The handle to the node that contains this kernel.
  * `[in]` _node_cmd_id_ - The kernel-specific command identifier for the node.
  * `[in]` _ref_ - The array of references.
  * `[in]` _num_refs_ - The number of references in the refs array.

*Returns:* An error code describing the status of the command .
// end::refpage:vx_kernel_command_f[]

== Functions

// tag::refpage:vxAddCommandToKernel[]
// [desc='',type='protos']
=== vxAddCommandToKernel
indexterm:[Node Send Command API, vxAddCommandToKernel]
// Brief text:
`[*REQ-NC03*]`[[REQ-NC03]] Allows users to add a control command callback to the kernel.

include::api/protos/vxAddCommandToKernel.txt[]

// Detailed text:
This function can be optionally called when creating a user kernel to register a command callback function with the kernel

*Parameters*

  * `[in]` _kernel_           - The reference to the kernel added with `<<vxAddUserKernel>>`.
  * `[in]` _command_func_ptr_ - The process-local function pointer to be invoked when application calls `<<vxNodeSendCommand>>`.

*Returns:* A `<<vx_status_e>>` enumerated value.

*Return Values*

  * `<<VX_SUCCESS,VX_SUCCESS>>` `[*REQ-NC04*]`[[REQ-NC04]] Command callback is successfully set on kernel; any other value indicates failure .
  * `<<VX_ERROR_INVALID_REFERENCE,VX_ERROR_INVALID_REFERENCE>>` - kernel is not a valid `<<vx_kernel>>` reference.
  * `<<VX_ERROR_INVALID_PARAMETERS,VX_ERROR_INVALID_PARAMETERS>>` - If the parameter is not valid for any reason.

*Precondition:* `<<vxAddUserKernel>>`
// end::refpage:vxAddCommandToKernel[]

// tag::refpage:vxNodeSendCommand[]
// [desc='',type='protos']
=== vxNodeSendCommand
indexterm:[Node Send Command API, vxNodeSendCommand]

// Brief text:
`[*REQ-NC05*]`[[REQ-NC05]] Send node-specific control command

include::api/protos/vxNodeSendCommand.txt[]

// Detailed text:
This is used to send a specific control command to the specified node asynchronously.
Not all nodes support commands, so refer to the node documentation for the specific control command.

- `[*REQ-NC06*]`[[REQ-NC06]] Note that this blocks for at most 'timeout' milli-seconds; i.e. this returns either when the command execution finishes or when the timeout occurs, whichever occurs first.
- `[*REQ-NC07*]`[[REQ-NC07]] Multiple commands can be sent to same or different nodes from different threads.

*Parameters*

* `[in]` _node_                     - Reference of the node to which this command is to be sent.
* `[in]` _replicate_nodex_idx_      
                                    - `[*REQ-NC08*]`[[REQ-NC08]] In case of a non-replicated node this should be 0. 
                                      For a replicated node this is the index of the node replica to which the command is targeted.
                                    - `[*REQ-NC09*]`[[REQ-NC09]] To send same command to all replicated nodes use `<<VX_CONTROL_CMD_SEND_TO_ALL_REPLICATED_NODES,VX_CONTROL_CMD_SEND_TO_ALL_REPLICATED_NODES>>`
* `[in]` _node_cmd_id_              - The Node-specific control command id
                                    - `[*REQ-NC10*]`[[REQ-NC10]]Node-specific control command id, refer to node-specific documentation
* `[inout]` _ref_                   - List of references, they can be any OpenVX object, created using the create API
                                    - `[*REQ-NC11*]`[[REQ-NC11]] This is a list of references, required as parameters for this
                                      control command. They can be any OpenVX object, created using the create API.
                                      They are bidirectional parameters, can be used for INPUT, OUTPUT or both.
                                      Refer to node documentation to get details about the parameters required for given control command.
* `[in]` _num_refs_                 - Number of valid entries/references in ref[] array
                                    - `[*REQ-NC12*]`[[REQ-NC12]] Number of valid entries/references in ref[] array shall valid depending on the given control command
* `[in]` _timeout_                  - Timeout in units of msecs, 
                                      - `[*REQ-NC13*]`[[REQ-NC13]] Timeout in units of msecs, use `<<VX_TIMEOUT_WAIT_FOREVER,VX_TIMEOUT_WAIT_FOREVER>>` to wait forever
5
*Returns:* A `<<vx_status_e>>` enumerated value.

*Return Values*

  * `<<VX_SUCCESS,VX_SUCCESS>>` `[*REQ-NC14*]`[[REQ-NC14]] No errors; any other value indicates failure.
  * `<<VX_ERROR_INVALID_NODE,VX_ERROR_INVALID_NODE>>` - if the node parameter is not a valid node.
  * `<<VX_ERROR_GRAPH_NOT_VERIFIED,VX_ERROR_GRAPH_NOT_VERIFIED>>` - if the graph that the node is a part of is not yet verified
  * `<<VX_ERROR_INVALID_REFERENCE,VX_ERROR_INVALID_REFERENCE>>` - if one or more of the ref parameter references is not a valid reference.
  * `<<VX_ERROR_TIMEOUT,VX_ERROR_TIMEOUT>>` - if the operation exceeds the timeout value.
  * `<<VX_ERROR_INVALID_PARAMETERS,VX_ERROR_INVALID_PARAMETERS>>` - if any of the other parameters are not valid or out of bounds

*Precondition:* `<<vxVerifyGraph>>`

// end::refpage:vxNodeSendCommand[]
