// Copyright (c) 2018 Khronos Group. This work is licensed under a
// Creative Commons Attribution 4.0 International License; see
// http://creativecommons.org/licenses/by/4.0/

= The OpenVX^(TM)^ Installable Client Driver Loader Extension
:regtitle: pass:q,r[^®^]
The Khronos{regtitle} OpenVX Working Group; Editors: Radhakrishna Giduthuri, Xin Wang
:title-logo-image: images/Khronos_RGB.svg
:data-uri:
:icons: font
:toc2:
:toclevels: 3
:max-width: 100
:numbered:
:imagewidth: 800
:fullimagewidth: width="800"
:halfimagewidth: width="400"
:source-highlighter: coderay
// Various special / math symbols. This is easier to edit with than Unicode.
include::config/attribs.txt[]

// Paths to code examples and headers
:examples: examples
:headers: examples

image::images/OpenVX_RGB.svg[align="center",{halfimagewidth}]
include::copyright-spec.txt[]

<<<<

// Table of contents is inserted here
toc::[]

:leveloffset: 1


= The OpenVX Installable Client Driver Loader Extension


[[sec_overview]]
== Overview

The `vx_khr_icd` extension defines a simple mechanism through which the
Khronos installable client driver loader (ICD Loader) may expose multiple
separate vendor installable client drivers (Vendor ICDs) for OpenVX.
An application written against the ICD Loader will be able to access all
`vx_platform` exposed by all vendor implementations with the ICD Loader
acting as a demultiplexer.


[[sec_Dependencies]]
== Dependencies

OpenVX 1.0.1 or later


[[sec_external]]
== External Interface

The ICD Loader interface can be accessed by application using:

[source,c]
--------------------------------------
#include <VX/vx_khr_icd.h>
--------------------------------------

The `VX/vx_khr_icd.h` includes definition of a new object <<vx_platform>>
and new functions `<<vxIcdGetPlatforms>>`, `<<vxQueryPlatform>>`,
`<<vxCreateContextFromPlatform>>`.
An ICD compatible vendor implementation is required to implement the
function `<<vxCreateContextFromPlatform>>`.
And the implementation of `<<vxIcdGetPlatforms>>`, `<<vxQueryPlatform>>`,
and `struct _vx_platform` will be part of ICD Loader source.
See `<<group_icd>>` for further details.


[[sec_Inferring]]
== Inferring Vendor ICD Calls from Arguments

At every OpenVX function call, the ICD Loader infers the Vendor ICD function
to call from the ICD compatible object that is passed as the first argument.
All OpenVX objects are said to be ICD compatible if the struct
`_vx_reference` contains a placeholder for `vx_platform` as its first field,
as shown below:

[source,c]
--------------------------------------
struct _vx_reference {
    struct _vx_platform * platform;
    // ... remainder of internal data
};
--------------------------------------

The structure `_vx_platform` has a function pointer dispatch table which is
used to make direct calls to a particular vendor implementation.
All objects created from ICD compatible objects must be ICD compatible.

Functions which do not take ICD compatible object or a pointer to ICD
compatible object as its first argument needs to be implemented by ICD
Loader.
The OpenVX functions that are required for an implementation in ICD Loader
source are:

include::api/protos/vxFormatImagePatchAddress1d.txt[]
include::api/protos/vxFormatImagePatchAddress2d.txt[]
include::api/protos/vxCreateContext.txt[]

The ICD Loader's `<<vxCreateContext>>` implementation is required to pick
the default platform and to call the vendor specific implementation of
`vxCreateContextFromPlatform`.

The ICD Loader's `vxHint` implementation is required to check the OpenVX
version of the vendor implementation and handle function signature changes
between OpenVX 1.0.1 and OpenVX 1.1.


[[sec_Linux]]
== Vendor Enumerations on Linux

To enumerate vendor ICDs on Linux, the ICD Loader scans the files under
`/etc/OpenVX/vendors`.
For each file in this path, the ICD Loader opens the file as a text file.
The expected format for the file is a single line of text which specifies
the Vendor ICD's library.
If the Vendor ICD comes with a separate library for immediate mode functions
(VXU), the expected format for the file is a single line of text with OpenVX
and VXU libraries separated by semi-colon(;) in that order.

The ICD Loader will attempt to open that file as a shared object using
`dlopen()`.
Note that the library specified may be an absolute path or just a file name.

*EXAMPLE*

// @ Change type
[source,c]
--------------------------------------
If the following file exists
    /etc/OpenVX/vendors/VendorA.icd
and contains the text
    libopenvx.so;libvxu.so
then the ICD Loader will load the libraries "libopenvx.so" and "libvxu.so"
--------------------------------------


[[sec_Android]]
== Vendor Enumerations on Android

To enumerate vendor ICDs on Android, the ICD Loader scans the files under
`/system/vendor/Khronos/OpenVX/vendors/`.
For each file in this path, the ICD Loader opens the file as a text file.
The expected format for the file is a single line of text which specifies
the Vendor ICD's library.
If the Vendor ICD comes with a separate library for immediate mode functions
(VXU), the expected format for the file is a single line of text with OpenVX
and VXU libraries separated by semi-colon(;) in that order.

The ICD Loader will attempt to open that file as a shared object using
`dlopen()`.
Note that the library specified may be an absolute path or just a file name.

*EXAMPLE*

// @ Change type
[source,c]
--------------------------------------
If the following file exists
    /system/vendor/Khronos/OpenVX/vendors/VendorA.icd
and contains the text
    libopenvx.so
then the ICD Loader will load the library "libopenvx.so"
--------------------------------------


[[sec_Windows]]
== Vendor Enumerations on Windows

To enumerate Vendor ICDs on Windows, the ICD Loader scans the values in the
registry key `HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenVX\Vendors`.
For each value in this key which has `DWORD` data set to 0, the ICD Loader
opens the dynamic link library specified by the name of the value using
`LoadLibraryA`.
If the Vendor ICD comes with a separate library for immediate mode functions
(VXU), the expected format for the name of the value is a single line of
text with OpenVX and VXU libraries separated by semi-colon(;) in that order.

*EXAMPLE*

// @ Change type
[source,c]
--------------------------------------
If the registry contains the following value
    [HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenVX\Vendors]
    "c:\\vendor_a\\openvx.dll;c:\\vendor_a\\vxu.dll"=dword:00000000
then the ICD will open the libraries "c:\vendor_a\openvx.dll" and "c:\vendor_a\vxu.dll"
--------------------------------------


[[sec_sample_implementation]]
== ICD Compatible Khronos Sample Implementation

To make the sample implementation compatible with ICD implementation, the
following two changes are required:

// @ Change type
[source,sh]
--------------------------------------
1. Add "struct _vx_platform * platform;" as first field to
   "struct _vx_reference"
2. Every derived reference should copy "platform" from it's parent: add
   "ref->platform = context ? context->base.platform : NULL;" statement to
   vxInitReference()
3. Create a new vxCreateContextFromPlatform() which initializes
   context->base.platform with the function argument and performs same
   functionality as vxCreateContext().
--------------------------------------


[[sec_ICD_loader]]
== Sample Implementation of ICD Loader

An implementation of ICD Loader is available in `vx_khr_icd` folder of
sample implementation tree.
Use cmake to build ICD Loader library to a static library with the name
"`openvx`".
Applications that use ICD Loader library can use any ICD compatible vendor
implementation picked during run-time.

*Example: Build and Run Conformance Tests using ICD Loader*

// @ Change type
[source,c]
--------------------------------------
# Build ICD Loader sample implementation from vx_khr_icd folder
% pushd <path-to-sample-implementation-trunk>
% export OPENVX_DIR=$PWD
% popd
% mkdir -p build/vx_khr_icd
% cd build/vx_khr_icd
% cmake $OPENVX_DIR/vx_khr_icd
% make
% export VX_KHR_ICD_LIB=$PWD
% cd ../..

# Build OpenVX Conformance Tests using ICD Loader
% mkdir -p build/conformance_tests
% cd build/conformance_tests
% cmake -DOPENVX_INCLUDES=$OPENVX_DIR/include \
        -DOPENVX_LIBRARIES=$VX_KHR_ICD_LIB/libopenvx.a\;pthread\;dl\;m \
        $OPENVX_DIR/conformance_tests
% make

# Run Conformance Tests
# Note: use of sample implementation requires LD_LIBRARY_PATH to be set properly
% export VX_TEST_DATA_PATH=$OPENVX_DIR/conformance_tests/test_data
% <build binary path>/vx_test_conformance
--------------------------------------


[[sec_updates]]
== Updates to ICD Loader source code

The sample implementation tree has a python script
`vx_khr_icd/vx_khr_icd.py` to update ICD Loader source code from OpenVX
header files in `include/VX` folder.

[source,sh]
--------------------------------------
# To update vx_dispatch.h, vx_dispatch.c, and ../include/VX/vx_khr_icd.h files
# with the API in VX/vx_api.h, VX/vx_nodes.h, VX/vxu.h, and VX/vx_compatibility.h,
# run below command from vx_khr_icd folder
% python vx_khr_icd.py \
      ../include/VX/vx_api.h ../include/VX/vx_nodes.h \
      ../include/VX/vxu.h \
      ../include/VX/vx_compatibility.h

# To create ICD Loader source code for OpenVX 1.0.1:
#   - unzip extract openvx_sample_1.0.1.tar.bz2 in openvx_sample folder
#   - copy vx_khr_icd folder into openvx_sample folder
#   - run below command from openvx_sample/vx_khr_icd folder
% python vx_khr_icd.py
      ../include/VX/vx_api.h ../include/VX/vx_nodes.h \
      ../include/VX/vxu.h
--------------------------------------


[[sec_Contributors]]
== Contributors

  * Radhakrishna Giduthuri (radha.giduthuri@amd.com)


[[module_documentation]]
= Module Documentation


[[group_icd]]
== OpenVX ICD Loader API

// @brief
The OpenVX Installable Client Driver (ICD) Loader API.

// @details
The `vx_khr_icd` extension provides a mechanism for vendors to implement
Installable Client Driver (ICD) for OpenVX.
The OpenVX ICD Loader API provides a mechanism for applications to access
these vendor implementations.

// tag::group_icd:summary[]
*Typedefs*

  * `<<vx_platform>>`

*Functions*

  * `<<vxCreateContextFromPlatform>>`
  * `<<vxIcdGetPlatforms>>`
  * `<<vxQueryPlatform>>`

// end::group_icd:summary[]

// tag::group_icd:details[]
=== Typedefs

// tag::refpage:vx_platform[]
// [desc='',type='basetypes']
==== vx_platform

// Brief text:
Platform handle of an implementation.

include::api/basetypes/vx_platform.txt[]

// end::refpage:vx_platform[]

=== Functions

// tag::refpage:vxCreateContextFromPlatform[]
// [desc='',type='protos']
==== vxCreateContextFromPlatform

// Brief text:
Creates a `vx_context` from a `<<vx_platform>>`.

include::api/protos/vxCreateContextFromPlatform.txt[]


// Detailed text:
This creates a top-level object context for OpenVX from a platform handle.

*Returns:* The reference to the implementation context `vx_context`.
Any possible errors preventing a successful creation should be checked using
`vxGetStatus`.
// end::refpage:vxCreateContextFromPlatform[]

// tag::refpage:vxIcdGetPlatforms[]
// [desc='',type='protos']
==== vxIcdGetPlatforms

// Brief text:
Queries list of available platforms.

include::api/protos/vxIcdGetPlatforms.txt[]


// Detailed text:
*Parameters*

  * `[in]` _capacity_ - Maximum number of items that platform[] can hold.
  * `[out]` _platform[]_ - List of platform handles.
  * `[out]` _pNumItems_ - Number of platform handles returned.

*Returns:* A `vx_status_e` enumeration.

*Return Values*

  * `<<VX_SUCCESS,VX_SUCCESS>>` - No errors.
  * `<<VX_FAILURE,VX_FAILURE>>` - If no platforms are found.
// end::refpage:vxIcdGetPlatforms[]

// tag::refpage:vxQueryPlatform[]
// [desc='',type='protos']
==== vxQueryPlatform

// Brief text:
Queries the platform for some specific information.

include::api/protos/vxQueryPlatform.txt[]


// Detailed text:
*Parameters*

  * `[in]` _platform_ - The platform handle.
  * `[in]` _attribute_ - The attribute to query.
    Use one of the following: `VX_CONTEXT_VENDOR_ID`, `VX_CONTEXT_VERSION`,
    `VX_CONTEXT_EXTENSIONS_SIZE`, `VX_CONTEXT_EXTENSIONS`.
  * `[out]` _ptr_ - The location at which to store the resulting value.
  * `[in]` _size_ - The size in bytes of the container to which _ptr_ points.

*Returns:* A `vx_status_e` enumeration.

*Return Values*

  * `<<VX_SUCCESS,VX_SUCCESS>>` - No errors.
  * `<<VX_ERROR_INVALID_REFERENCE,VX_ERROR_INVALID_REFERENCE>>` - If the platform is not a
    `<<vx_platform>>`.
  * `<<VX_ERROR_INVALID_PARAMETERS,VX_ERROR_INVALID_PARAMETERS>>` - If any of the other parameters are
    incorrect.
  * `<<VX_ERROR_NOT_SUPPORTED,VX_ERROR_NOT_SUPPORTED>>` - If the attribute is not supported on this
    implementation.
// end::refpage:vxQueryPlatform[]

// end::group_icd:details[]
